### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ukmojb** [quentin452/MUP#10]
[crash-2023-08-22_18.12.24-client.txt](https://github.com/quentin452/MUP/files/12407688/crash-2023-08-22_18.12.24-client.txt)
[latest.log](https://github.com/quentin452/MUP/files/12407690/latest.log)
I added this mod to my modpackage and had a crash in the desert

**Comment by quentin452** [comment]
Can you make a screenshot of config?
Does you switched from mup original to the fork?


Try resetting the config

**Comment by ukmojb** [comment]
https://pastebin.com/Yh384845
This is config.
I'm using the fork directly
