### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ferreiraalex** [quentin452/MUP#9]
[crash-2023-08-14_02.15.45-server.txt](https://github.com/quentin452/MUP/files/12330608/crash-2023-08-14_02.15.45-server.txt)
[crash-2023-08-14_02.15.30-client.txt](https://github.com/quentin452/MUP/files/12330609/crash-2023-08-14_02.15.30-client.txt)

**Comment by quentin452** [comment]
Can you give the latest.log pls

**Comment by ferreiraalex** [comment]
https://cloud.mail.ru/public/xN59/zjHq2KPkG
[crash-2023-08-14_05.07.50-server.txt](https://github.com/quentin452/MUP/files/12331010/crash-2023-08-14_05.07.50-server.txt)
[crash-2023-08-14_05.03.36-client.txt](https://github.com/quentin452/MUP/files/12331011/crash-2023-08-14_05.03.36-client.txt)

**Comment by quentin452** [comment]
try disabling mc-121196

**Comment by ferreiraalex** [comment]
https://i.imgur.com/v3eLfyF.png
![javaw_P56C7wHhYU](https://github.com/quentin452/MUP/assets/10839855/4eee0b98-2cc0-4351-8b68-8abb0e57895b)
![javaw_8IBtg9YUcV](https://github.com/quentin452/MUP/assets/10839855/4496a7bb-04f8-4646-8954-74fc2acad211)
![javaw_41xzjXnk9d](https://github.com/quentin452/MUP/assets/10839855/3c61a98f-16cb-4c0f-842a-44dd638f5298)

**Comment by quentin452** [comment]
it seem that there is a problem , try redownloading mup and maybe update mixinbooter

**Comment by quentin452** [comment]
ok try this devbuild
https://mega.nz/file/K8lmySaC#3TquvaPzsgXDBKvLvKHK99JLNSpSk0TFQy74DrdFjN4

**Comment by ferreiraalex** [comment]
not fixed?

**Comment by quentin452** [comment]
you need to try it , i can't reproduce your issue , but the devbuild should fix it

**Comment by quentin452** [comment]
if you say , the issue is fixed , i will close the issue

**Comment by ferreiraalex** [comment]
ok give me time
